name: CI/CD Workflow

on:
  push:
    branches: [ develop, HML, main ]
  pull_request:
    branches: [ develop ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

  build-desktop-app:
    runs-on: ubuntu-latest
    needs: test-backend
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build Desktop App
      run: npm run build
    - name: Package App for Release
      run: npm run package
      # Assumindo que você tem um script 'package' configurado para empacotar sua aplicação Electron

  deploy-to-hml:
    runs-on: ubuntu-latest
    needs: build-desktop-app
    if: github.ref == 'refs/heads/HML'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Backend to AWS
      run: echo "Deploying backend to AWS..."
      # Aqui você adicionaria comandos ou utiliza ferramentas como AWS CLI para fazer o deploy do backend na AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' # Exemplo de região

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build-desktop-app
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Backend to AWS Production
      run: echo "Deploying backend to AWS Production..."
      # Comandos para deploy do backend em produção na AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' # Exemplo de região
